name: Build and Deploy
on: # 触发条件
  push:    # 有推送时触发
    branches:
      - main
  # 定时器
  # schedule:
  #   # 分 时 日期 月份 星期 
  #   # 时 需要 +8 表示北京时间
  #   - cron: '0 0,4,10,15 * * 1-5'
jobs:
  push-empty-code: 
    runs-on: ubuntu-latest
    steps:
      - name: create file
        run: echo '123'
    # - name: test
    #   run: echo 'hello world' && git -v && echo 'hello world1'
       

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout 🛎
  #     uses: actions/checkout@v2.3.1

  #   - name: Install node
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '12'

  #   - name: exec
  #     run: npm install && npm run exec
